version: '3.3'
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: grpc
    ports:
      - "8081:8080"
    volumes:
      - ./swagger:/usr/share/nginx/html/swagger
    environment:
      API_URL: swagger/api.swagger.json
