// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.0
// source: api_pb.proto

package pb

import (
	context "context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InnRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inn string `protobuf:"bytes,1,opt,name=inn,proto3" json:"inn,omitempty"`
}

func (x *InnRequest) Reset() {
	*x = InnRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InnRequest) ProtoMessage() {}

func (x *InnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InnRequest.ProtoReflect.Descriptor instead.
func (*InnRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_proto_rawDescGZIP(), []int{0}
}

func (x *InnRequest) GetInn() string {
	if x != nil {
		return x.Inn
	}
	return ""
}

type InnResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inn     string `protobuf:"bytes,1,opt,name=inn,proto3" json:"inn,omitempty"`
	Kpp     string `protobuf:"bytes,2,opt,name=kpp,proto3" json:"kpp,omitempty"`
	Name    string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CeoName string `protobuf:"bytes,4,opt,name=ceo_name,json=ceoName,proto3" json:"ceo_name,omitempty"`
}

func (x *InnResponse) Reset() {
	*x = InnResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InnResponse) ProtoMessage() {}

func (x *InnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InnResponse.ProtoReflect.Descriptor instead.
func (*InnResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_proto_rawDescGZIP(), []int{1}
}

func (x *InnResponse) GetInn() string {
	if x != nil {
		return x.Inn
	}
	return ""
}

func (x *InnResponse) GetKpp() string {
	if x != nil {
		return x.Kpp
	}
	return ""
}

func (x *InnResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InnResponse) GetCeoName() string {
	if x != nil {
		return x.CeoName
	}
	return ""
}

var File_api_pb_proto protoreflect.FileDescriptor

var file_api_pb_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x61, 0x70, 0x69, 0x5f, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x61, 0x70, 0x69, 0x5f, 0x70, 0x62, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1e, 0x0a, 0x0a, 0x49, 0x6e, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x6e, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x69, 0x6e, 0x6e, 0x22, 0x60, 0x0a, 0x0b, 0x49, 0x6e, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x6e, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x69, 0x6e, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x70, 0x70, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x70, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x63,
	0x65, 0x6f, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x65, 0x6f, 0x4e, 0x61, 0x6d, 0x65, 0x32, 0x59, 0x0a, 0x0a, 0x49, 0x6e, 0x6e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x4b, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x42,
	0x79, 0x49, 0x6e, 0x6e, 0x12, 0x12, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x70, 0x62, 0x2e, 0x49, 0x6e,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x70,
	0x62, 0x2e, 0x49, 0x6e, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x12, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x0c, 0x12, 0x0a, 0x2f, 0x69, 0x6e, 0x6e, 0x2f, 0x7b, 0x69, 0x6e, 0x6e,
	0x7d, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_pb_proto_rawDescOnce sync.Once
	file_api_pb_proto_rawDescData = file_api_pb_proto_rawDesc
)

func file_api_pb_proto_rawDescGZIP() []byte {
	file_api_pb_proto_rawDescOnce.Do(func() {
		file_api_pb_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_pb_proto_rawDescData)
	})
	return file_api_pb_proto_rawDescData
}

var file_api_pb_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_pb_proto_goTypes = []interface{}{
	(*InnRequest)(nil),  // 0: api_pb.InnRequest
	(*InnResponse)(nil), // 1: api_pb.InnResponse
}
var file_api_pb_proto_depIdxs = []int32{
	0, // 0: api_pb.InnService.GetInfoByInn:input_type -> api_pb.InnRequest
	1, // 1: api_pb.InnService.GetInfoByInn:output_type -> api_pb.InnResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_pb_proto_init() }
func file_api_pb_proto_init() {
	if File_api_pb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_pb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InnRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InnResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_pb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_pb_proto_goTypes,
		DependencyIndexes: file_api_pb_proto_depIdxs,
		MessageInfos:      file_api_pb_proto_msgTypes,
	}.Build()
	File_api_pb_proto = out.File
	file_api_pb_proto_rawDesc = nil
	file_api_pb_proto_goTypes = nil
	file_api_pb_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// InnServiceClient is the client API for InnService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InnServiceClient interface {
	GetInfoByInn(ctx context.Context, in *InnRequest, opts ...grpc.CallOption) (*InnResponse, error)
}

type innServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInnServiceClient(cc grpc.ClientConnInterface) InnServiceClient {
	return &innServiceClient{cc}
}

func (c *innServiceClient) GetInfoByInn(ctx context.Context, in *InnRequest, opts ...grpc.CallOption) (*InnResponse, error) {
	out := new(InnResponse)
	err := c.cc.Invoke(ctx, "/api_pb.InnService/GetInfoByInn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InnServiceServer is the server API for InnService service.
type InnServiceServer interface {
	GetInfoByInn(context.Context, *InnRequest) (*InnResponse, error)
}

// UnimplementedInnServiceServer can be embedded to have forward compatible implementations.
type UnimplementedInnServiceServer struct {
}

func (*UnimplementedInnServiceServer) GetInfoByInn(context.Context, *InnRequest) (*InnResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInfoByInn not implemented")
}

func RegisterInnServiceServer(s *grpc.Server, srv InnServiceServer) {
	s.RegisterService(&_InnService_serviceDesc, srv)
}

func _InnService_GetInfoByInn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InnServiceServer).GetInfoByInn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api_pb.InnService/GetInfoByInn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InnServiceServer).GetInfoByInn(ctx, req.(*InnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _InnService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api_pb.InnService",
	HandlerType: (*InnServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfoByInn",
			Handler:    _InnService_GetInfoByInn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api_pb.proto",
}
